version: '3.8'
name: canihost

services:
  app:
    image: monooso/canihost:latest
    container_name: monooso-canihost-app
    restart: unless-stopped
    env_file:
      - app.env
    environment:
      LETSENCRYPT_HOST: canihost.stephenlewis.me
      VIRTUAL_HOST: canihost.stephenlewis.me
      VIRTUAL_PORT: 4000
    networks:
      - canihost
      - flyby

  db:
    image: postgres:latest
    container_name: monooso-canihost-db
    restart: unless-stopped
    env_file:
      - db.env
    networks:
      - canihost
    ports:
      - "${TAILSCALE_IP}:5432:5432"

networks:
  canihost:
    name: canihost
  flyby:
    external: true
    name: flyby
