version: '3.8'
name: canihost

services:
  app:
    image: monooso/canihost:latest
    container_name: monooso-canihost
    restart: unless-stopped
    env_file:
      - docker.env
    environment:
      LETSENCRYPT_HOST: canihost.stephenlewis.me
      VIRTUAL_HOST: canihost.stephenlewis.me
      VIRTUAL_PORT: 4000
    networks:
      - canihost
      - flyby

networks:
  canihost:
    name: canihost
  flyby:
    external: true
    name: flyby
